# Generated by Django 5.2.3 on 2025-07-16 06:39

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0001_initial'),
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the skill (e.g., Python, Project Management)', max_length=50, unique=True, verbose_name='Skill Name')),
                ('category', models.CharField(blank=True, help_text='General category this skill belongs to', max_length=50, null=True, verbose_name='Skill Category')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture')),
                ('headline', models.CharField(blank=True, max_length=120, null=True, verbose_name='Professional Headline')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Professional Summary')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Contact Phone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Personal Website / Portfolio')),
                ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile')),
                ('github_profile', models.URLField(blank=True, null=True, verbose_name='GitHub Profile')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primary Profession')),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Employer')),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)], verbose_name='Years of Experience')),
                ('work_experience', models.TextField(blank=True, null=True, verbose_name='Work Experience')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Highest Education')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Certifications')),
                ('is_willing_to_relocate', models.BooleanField(default=False, verbose_name='Willing to Relocate')),
                ('is_remote_preferred', models.BooleanField(default=False, verbose_name='Prefers Remote Work')),
                ('availability_status', models.CharField(choices=[('actively_looking', 'Actively looking'), ('open_to_offers', 'Open to offers'), ('not_looking', 'Not currently looking')], default='open_to_offers', max_length=50, verbose_name='Availability Status')),
                ('desired_salary_range', models.CharField(blank=True, max_length=50, null=True, verbose_name='Desired Salary Range')),
                ('job_search_preferences', models.TextField(blank=True, null=True, verbose_name='Job Search Preferences')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Resume / CV')),
                ('cover_letter_template', models.FileField(blank=True, null=True, upload_to='cover_letters/', verbose_name='Cover Letter Template')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Professional')),
                ('is_profile_public', models.BooleanField(default=True, verbose_name='Public Profile')),
                ('job_interest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seekers', to='core.location', verbose_name='Preferred Job Location')),
                ('job_role_interests', models.ManyToManyField(blank=True, related_name='interested_professionals', to='Jobs.jobcategory', verbose_name='Preferred Job Roles')),
                ('job_type_interests', models.ManyToManyField(blank=True, related_name='interested_professionals', to='Jobs.jobtype', verbose_name='Preferred Job Types')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location', verbose_name='Current Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
                ('skills', models.ManyToManyField(blank=True, related_name='professionals', to='professionals.skill', verbose_name='Skills & Competencies')),
            ],
            options={
                'verbose_name': 'Professional Profile',
                'verbose_name_plural': 'Professional Profiles',
                'ordering': ['user__first_name'],
            },
        ),
    ]
